---@meta
---@module 'gopath.@types.env_path'

---@class EnvPathOptions
---@field enable boolean
--- Whether to resolve environment variables in paths (default: true).
--- When enabled, tokens like $REPOS_DIR/foo.md or ${REPOS_DIR}/foo.md
--- are expanded before file resolution.
---@field shorten_dirs table<string, string>
--- Segment-name -> env-var-name map used by :GopathToReposDir /
--- :Gopath to-repos-dir — the reverse direction. Structural, not literal: a
--- path whose root segment is the key (e.g. "repos") -- under any drive
--- letter/OS, and regardless of what the named var actually resolves to on
--- this machine -- is rewritten to `$<value>`.
--- Default: { repos = "REPOS_DIR" }.

---@class EnvPathResult
---@field raw string    The original token before expansion (e.g., "$REPOS_DIR/foo.md")
---@field expanded string  The expanded absolute path
---@field var_name string  The environment variable name that was resolved
---@field var_value string The resolved value of the variable
